# Generated by Django 5.1.1 on 2024-09-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_created_accounts_and_transactions"),
    ]

    operations = []
