# Generated by Django 5.1.1 on 2024-09-17 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_removed_extra_user_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allpermtransaction",
            name="transaction_ts",
        ),
        migrations.RemoveField(
            model_name="postonlytransaction",
            name="transaction_ts",
        ),
        migrations.RemoveField(
            model_name="viewonlytransaction",
            name="transaction_ts",
        ),
        migrations.AddField(
            model_name="allpermtransaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="postonlytransaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="viewonlytransaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
